name: Generate GitHub Trophy

on:
  schedule:
    - cron: "0 0 * * *" # atualiza uma vez por dia
  workflow_dispatch: {} # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate trophy.svg
        uses: ryo-ma/github-profile-trophy@v1.0
        with:
          username: felipe2008pg1
          output_path: trophy.svg
          token: ${{ secrets.TROPHY_TOKEN }}

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git diff --staged --quiet || git commit -m "chore: update trophy.svg"
          git push
